CREATE TABLE [dbo].[movies]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Title] NVARCHAR(MAX) NOT NULL, 
    [Description] NVARCHAR(MAX) NULL, 
    [ImageUrl] NVARCHAR(MAX) NULL, 
    [Created] DATETIME NOT NULL DEFAULT GETUTCDATE()
)
